In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


NumPy (Numerical Python) is a foundational open-source library used for scientific computing and data analysis in Python. It provides support for large, multi-dimensional arrays and matrices, alongside a massive collection of high-level mathematical functions to operate on these structures.

In [1]:
import numpy as np 

#  create array using numpy 
#  create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr2=np.array([[1,2,3,4,5], 
               [6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [6]:
np.arange(0, 10, 2).reshape(5,1) # 0 to 10 with step size of 2

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3) # identity matrix of size 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# 1. Create a sample 3D array (tensor) to demonstrate multi-dimensional attributes
# Shape: 2 blocks, 3 rows, 4 columns
matrix_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
    [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]
], dtype=np.int64)

# 2. Inspecting and printing the core NumPy attributes
print("=== NumPy Array Attribute Inspection ===")
print(f"Array Target:\n{matrix_3d}\n")
print(f"1. .ndim (Dimensions)      : {matrix_3d.ndim}")
print(f"2. .shape (Dimensions Size): {matrix_3d.shape}")
print(f"3. .size (Total Elements)  : {matrix_3d.size}")
print(f"4. .dtype (Data Type)      : {matrix_3d.dtype}")
print(f"5. .itemsize (Size/Element): {matrix_3d.itemsize} bytes")
print(f"6. .nbytes (Total Memory)  : {matrix_3d.nbytes} bytes")

# 3. Verification check to prove the relationship between metadata attributes
assert matrix_3d.nbytes == matrix_3d.size * matrix_3d.itemsize
print("\n[Assertion Passed]: .nbytes strictly equals .size * .itemsize")

=== NumPy Array Attribute Inspection ===
Array Target:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

1. .ndim (Dimensions)      : 3
2. .shape (Dimensions Size): (2, 3, 4)
3. .size (Total Elements)  : 24
4. .dtype (Data Type)      : int64
5. .itemsize (Size/Element): 8 bytes
6. .nbytes (Total Memory)  : 192 bytes

[Assertion Passed]: .nbytes strictly equals .size * .itemsize


In [10]:
### Numpy Vectorized Operations
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([10, 20, 30, 40, 50])

## Element-wise Addition
print("Addition:", arr1 + arr2)

## Element-wise Subtraction
print("Subtraction:", arr1 - arr2)

## Element-wise Multiplication
print("Multiplication:", arr1 * arr2)   

## Element-wise Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [12]:
## Universal Functions (ufuncs) - Applying mathematical functions to arrays
arr = np.array([1, 2, 3, 4, 5, 6])

## Square Root
print("Square Root:", np.sqrt(arr))

## Exponential
print("Exponential:", np.exp(arr))

## Natural Logarithm
print("Natural Logarithm:", np.log(arr))

## Sine Function
print("Sine:", np.sin(arr))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [14]:
# Array Indexing and Slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

# Accessing individual elements
print("First element:", arr[0, 0])
print("Last element:", arr[-1, -1])

# Slicing
print("First three rows:", arr[0:3])
print("Rows from index 1 to 3:", arr[1:4])
print("First three columns:", arr[:, 0:3])
print("Columns from index 1 to 3:", arr[:, 1:4])


First element: 1
Last element: 15
First three rows: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Rows from index 1 to 3: [[ 6  7  8  9 10]
 [11 12 13 14 15]]
First three columns: [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
Columns from index 1 to 3: [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [17]:
#application concepts --normalization 

## to have a mean of 0 and standard deviation of 1, we can use the following formula:
## normalized_value = (value - mean) / standard_deviation

data = np.array([10, 20, 30, 40, 50])
print(data)

mean = np.mean(data)
print("Mean:", mean)
    
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

normalized_data = (data - mean) / std_dev
print("Normalized Data:", normalized_data)

#variance and standard deviation
variance = np.var(data)
print("Variance:", variance)

[10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
Variance: 200.0


In [18]:
# logical operations and boolean indexing
data = np.array([10, 20, 30, 40, 50])
# Create a boolean mask for values greater than 25
mask = data > 25
print("Boolean Mask:", mask)

# Use the boolean mask to filter the array
filtered_data = data[mask]
print("Filtered Data (values > 25):", filtered_data)


Boolean Mask: [False False  True  True  True]
Filtered Data (values > 25): [30 40 50]
